<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Neelam" failures="1" tests="2" name="ErroValidationTest" time="26.895" errors="0" timestamp="2024-06-10T12:05:02 EDT">
  <testcase classname="Tests.ErrorValidationTest" name="productErrorValidation" time="10.217">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Tests.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="Tests.ErrorValidationTest" name="submitOrder" time="1.251"/>
</testsuite> <!-- ErroValidationTest -->
